### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by i0n1ca** [flopreynat/Embedded-timelines-with-API-V1.1-OAuth#1]
Hello,

Great work on this plugin. I would like to use my last tweet on my timeline page. I use a blog, so above the first post I want to display my last tweet.

How I can do that?

Thanks.

**Comment by flopreynat** [comment]
hey mate, did you read the blog post? it's all explained.
I can't make it more precise, as it needs YOUR own credentials. 

good luck,

$consumer_key = 'xxxxxxxxxxxxxxxxxxxxxx';  
$consumer_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
$access_token = 'xxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
$access_token_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';

**Comment by i0n1ca** [comment]
I was trying to say that I want the output of index.php form to be displayed on my website above the first post. Anyway I've found a way by my self and got that code displayed. 
Here is my website http://www.iSay.ro

Thanks any way.
